ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;  

CREATE USER SINUEDU IDENTIFIED BY SINUEDU;           

GRANT CONNECT, RESOURCE, CREATE SEQUENCE TO SINUEDU;

ALTER USER SINUEDU DEFAULT TABLESPACE SYSTEM
QUOTA UNLIMITED ON SYSTEM;